environment:
  matrix:
    - nodejs_version: 14.3.0
      platform: x86
      NODE_OPTIONS: --trace-event-categories=node.async_hooks
    - nodejs_version: 14.2.0
      platform: x86
      NODE_OPTIONS: --trace-event-categories=node.async_hooks
    - nodejs_version: 14.3.0
      platform: x86
    - nodejs_version: 14.2.0
      platform: x86

os: Visual Studio 2015

install:
- ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
- where node
- node --version
- build-appveyor.bat

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build: OFF
test: OFF
deploy: OFF
