environment:
  matrix:
    - nodejs_version: 14
      platform: x86

os: Visual Studio 2015

install:
- ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
- where node
- node --version
- build-appveyor.bat

build: OFF
test: OFF
deploy: OFF
